services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=EST
    volumes:
      - /home/jarrett/sonarr/data:/config
      - /media/plex/tv:/tv
      - /media/plex/sab/downloads:/downloads
      - /media/plex/sab/incomplete:/incomplete
    ports:
      - 8989:8989
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(`${SUBDOMAIN}.${DOMAIN_NAME}`)"
      - "traefik.http.routers.sonarr.entrypoints=web, websecure"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
#      - "traefik.http.routers.sonarr.tls.certresolver=mytlschallenge"
      - "traefik.http.routers.sonarr.tls=true"
networks:
  default:
    name: traefik_default
    external: true